"""Generate docs/alert_catalog.md FROM config/alerts.yaml so the two
cannot drift. Re-run after editing the catalog:

    python3 scripts/gen_alert_docs.py

Layer: tooling (imports yaml + stdlib only). Not part of any runtime layer.
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "config" / "alerts.yaml"
OUT = ROOT / "docs" / "alert_catalog.md"

# What each alert is CONSTRUCTED FROM: the concrete input fields the engine
# reads to build it. Keyed by alert id. Kept next to the generator so the
# 'built from' column is explicit rather than guessed from the yaml.
BUILT_FROM: dict[str, str] = {
    "rogue_ap_on_wire":
        "Air Marshal `wiredMacs`, `wiredVlans`, `bssid`, `channel` "
        "(via dlai.attack AttackAnalyzer -> AttackAssessment kind "
        "`rogue_ap_on_wire`)",
    "rogue_ap_on_pos_vlan":
        "Air Marshal `wiredMacs`, `wiredVlans` intersected with the POS "
        "VLAN set; escalated from the same `rogue_ap_on_wire` assessment",
    "evil_twin_ops_ssid":
        "Air Marshal `ssid` resembling an own SSID with `wiredMacs` EMPTY "
        "(AttackAssessment kind `honeypot_ssid`)",
    "deauth_flood":
        "aWIPS syslog `signature`+`apMac`+`gap` (AttackAssessment kind "
        "`awips_deauth_flood`); carries NO frame count by design",
    "containment_active_rtls_risk":
        "the gap flag `containment_rtls_degraded` on any Scanning-API "
        "observation, or `contained=true` / that gap on an Air Marshal record",
    "cart_mac_duplicate":
        "two Scanning-API observations for one cart-OUI `clientMac`, each "
        "with a `cloud_location` (inferred), displaced beyond threshold in "
        "under the window",
    "cart_impossible_motion":
        "a run of Scanning-API `cloud_location` fixes for one cart-OUI "
        "`clientMac` whose segment speeds exceed the cart cap "
        "(sustained, not a single fix)",
    "probe_surge_unassociated":
        "count of distinct unassociated `clientMac`s (ssid absent) inside a "
        "sliding window over Scanning-API observations",
    "sensor_silent":
        "per-AP last-seen time built from `rssiRecords[].apMac` across "
        "observations; fires when an AP is absent past the silent window",
    "exit_without_checkout":
        "dlai.policy Recommendation `exit_without_checkout_presence` "
        "(subject_mac + exit evidence), passed through unchanged",
    "neighbour_network_catalogued":
        "Air Marshal `bssid`+`ssid` with `wiredMacs` EMPTY and not "
        "resembling an own SSID (AttackAssessment kind `neighbour_network`)",
}

IMPLEMENTED = {
    "rogue_ap_on_wire", "rogue_ap_on_pos_vlan", "evil_twin_ops_ssid",
    "deauth_flood", "containment_active_rtls_risk", "cart_mac_duplicate",
    "cart_impossible_motion", "probe_surge_unassociated", "sensor_silent",
    "exit_without_checkout", "neighbour_network_catalogued",
}

INTRO = """# Alert catalog — what each alert is built from

> **Generated from `config/alerts.yaml` by `scripts/gen_alert_docs.py`.**
> Do not edit this file by hand — edit the YAML and regenerate, so the
> human-readable catalog can never drift from the machine-readable one.
> `tests/test_alerts.py` asserts every catalog id appears here.

This is the human companion to `config/alerts.yaml`. The alerts are
defined by **this building's context**, not generic IDS signatures: five
neighbour Wi-Fi networks share the floor, aWIPS is throttled and carries
no client identity, containment degrades RTLS floor-wide, RF cannot tell
inside from outside, and position flicker makes single fixes untrustworthy.

## Anatomy of an alert

Every `Alert` the engine emits (`dlai/alerts.py`) is:

| field | why it exists |
|---|---|
| `t_ms` | one clock, UTC ms — when the evidence timestamped, never a wall-clock read |
| `alert_id` | the catalog id that fired; the join key to this document |
| `severity` | `info` / `warn` / `high` — set by the catalog, not by the engine |
| `subject` | the thing the alert is about (a BSSID, an AP MAC, a cart MAC) |
| `action` | a **recommendation sentence** for a human operator — never an enforcement |
| `evidence` | the exact input fields the alert was constructed from — provenance |
| `confidence` | `observed` **only** for directly-heard facts (wire evidence, an aWIPS report); `inferred` for anything computed (a position, a duplicate, a silence). **An inference must never masquerade as an observation** — that is the whole discipline of the three-layer split. |
| `mode` | always `RECOMMEND_ONLY` — the PoC recommends, it does not act |
| `blind_spots` | what this alert **cannot know**: intensity lost to aWIPS throttling, inside/outside indiscriminable by RF, single fixes untrusted under flicker. Stated so an operator never over-reads the alert. |

**Deliberate non-alerts** (never added back): downlink RSSI anomalies
(RRM moves AP Tx power 2-26 dBm every 30 min — expected), and any claim
that a device is physically "inside" or "outside" the store on RF alone
(the 18 perimeter units cannot separate it).

## The alerts
"""

SEV_ORDER = {"high": 0, "warn": 1, "info": 2}


def _fmt_conditions(cond: dict) -> str:
    if not cond:
        return "_none_"
    parts = []
    for k, v in cond.items():
        parts.append(f"`{k}` = `{v}`")
    return "; ".join(parts)


def _fmt_list(items) -> str:
    return "".join(f"\n  - {i}" for i in items) if items else " _none_"


def render() -> str:
    doc = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    meta = doc.get("meta", {})
    entries = sorted(doc["alerts"],
                     key=lambda e: (SEV_ORDER.get(e["severity"], 9), e["id"]))

    out = [INTRO]
    out.append(f"\n_Mode: **{meta.get('mode')}**. Dedup window: "
               f"`{meta.get('dedup_window_ms')}` ms "
               f"(one alert per `alert_id`+`subject` per window)._\n")

    for e in entries:
        impl = "implemented in the engine" if e["id"] in IMPLEMENTED \
            else "catalog-only (not yet wired in the engine)"
        out.append(f"\n### `{e['id']}` — {e['title']}\n")
        out.append(f"- **Severity:** {e['severity']}  ({impl})")
        out.append(f"- **Source stream(s):** {', '.join(e['streams'])}")
        out.append(f"- **Built from:** {BUILT_FROM.get(e['id'], '_see engine_')}")
        out.append(f"- **Context threshold(s) & provenance:** "
                   f"{_fmt_conditions(e.get('context_conditions', {}))}")
        out.append(f"- **Evidence required:** "
                   f"{', '.join(f'`{f}`' for f in e['evidence_required'])}")
        out.append(f"- **Recommendation (action):** {' '.join(e['action'].split())}")
        out.append(f"- **Known blind spots:**{_fmt_list(e['known_blind_spots'])}")

    out.append("\n---\n")
    out.append("Provenance comments for every threshold live inline in "
               "`config/alerts.yaml`. This file is regenerated from it.\n")
    return "\n".join(out)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
